version: '3.8'  # Define the version of the Docker Compose file format

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Maps port 3000 on the host to port 3000 on the container
    env_file:
      - .env
    volumes:
      - .:/app  # Mounts the current directory on the host to /app in the container
      - /app/node_modules  # Ensures node_modules inside the container are used
    environment:
      - NODE_ENV=development  # Set environment to development
      - MONGO_URI=mongodb://mongo:27017/express_authNew  # MongoDB connection string
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5000

    depends_on:
      - mongo  # Ensure MongoDB starts before the app
    command: npm run dev  # Start the application using npm run watch
    networks:
      - app-network  # Connects to the custom network

  mongo:
    image: mongo:latest  # Uses the latest MongoDB image from Docker Hub
    ports:
      - "27017:27017"  # Exposes MongoDB's default port to the host
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data across container restarts
      - .env:/app/.env
    networks:
      - app-network  # Connects to the custom network

volumes:
  mongo-data:  # Defines a named volume for MongoDB data persistence

networks:
  app-network:
    driver: bridge  # Use the default bridge network
